// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RCP.DB.Infrastructure;

#nullable disable

namespace RCP.DB.Infrastructure.Migrations
{
    [DbContext(typeof(RcpContext))]
    [Migration("20220313194007_SaveLoginToProgrammingWorkingTime")]
    partial class SaveLoginToProgrammingWorkingTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("jenkins_job_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("programmer_working_time_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("project_hilo")
                .IncrementsBy(10);

            modelBuilder.Entity("RCP.DB.Model.JenkinsJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "jenkins_job_hilo");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("BuildTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Culprit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JenkinsJob", (string)null);
                });

            modelBuilder.Entity("RCP.DB.Model.Programmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Programmer", (string)null);
                });

            modelBuilder.Entity("RCP.DB.Model.ProgrammerWorkingTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "programmer_working_time_hilo");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgrammerId")
                        .HasColumnType("int");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammerId");

                    b.ToTable("ProgrammerWorkingTime", (string)null);
                });

            modelBuilder.Entity("RCP.DB.Model.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "project_hilo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("RCP.DB.Model.Programmer", b =>
                {
                    b.HasOne("RCP.DB.Model.Project", "Project")
                        .WithMany("Programmers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RCP.DB.Model.ProgrammerWorkingTime", b =>
                {
                    b.HasOne("RCP.DB.Model.Programmer", null)
                        .WithMany("ProgrammersWorkingTime")
                        .HasForeignKey("ProgrammerId");
                });

            modelBuilder.Entity("RCP.DB.Model.Programmer", b =>
                {
                    b.Navigation("ProgrammersWorkingTime");
                });

            modelBuilder.Entity("RCP.DB.Model.Project", b =>
                {
                    b.Navigation("Programmers");
                });
#pragma warning restore 612, 618
        }
    }
}
